### PR TITLE
Add dev installation section

### PR DESCRIPTION
**Pull request by G07cha**
Guide to setup app for development but for now I've expecting issue when using `npm start` command.

Please, don't merge it until #7 don't be fixed

### CODE REVIEW

**Comment by rhysd** [comment]
Did you really try this sequence?  I think `rake build` is needed to compile TypeScript codes.  Please confirm that the sequence succeeds at least in your environment before sending pull request.

**Comment by G07cha** [comment]
As I mentioned here is an issue #7 that blocks following guide, I'll try `rake build` and if it succeed we have 2 options. Update guide or update `package.json` file.

**Comment by G07cha** [comment]
Find the way to run app, it requires `tsd` module installed globally and as you said compiled TypeScript. Should we add preinstall hook to `package.json`?

**Comment by rhysd** [comment]
OK, I'll write instruction to README.  Could you check it?

**Comment by G07cha** [comment]
Sure, I also can update this pr with correct instruction.

**Comment by rhysd** [comment]
I wrote.

https://github.com/rhysd/Trendy#development

Could you try this?

**Comment by G07cha** [comment]
Yep, It's correct.

**Comment by rhysd** [comment]
Thank you for the confirmation.  It was helpful.

**Comment by G07cha** [comment]
You are welcome.

**Pull request closed without merging**
